# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'myapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for myapp
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/RemoteConfig'
  
  target 'myapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'myappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
